version: '3.8'

services:
  ai-worker-kp:
    deploy:
      resources:
        limits:
          memory: 32G # Allow more RAM on the powerful server
        reservations:
          memory: 16G
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
